import type { Provider } from "./types";

/** Featured tour operators */
export const TOUR_OPERATORS: Provider[] = [
{
    id: "TO001",
    name: "Richmond Holidays",
    website: "https://www.richmond-holidays.com/",
    category: "tours",
    subCategory: "Beach / Ski / Activity",
    location: "UK",
    description:
      "Quality Christian holidays offering ski weeks, beach resorts, walking weeks, and solo traveller programmes with dedicated ministry staff, worship and prayer.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Solo traveller weeks", "Walking holidays", "Ski holidays", "Ministry staff on site"],
    tags: ["Interdenominational", "Beach", "Ski", "Walking"],
    targetAudience: "Families, Singles, Couples, Walking enthusiasts",
    featured: true,
  },
  {
    id: "TO002",
    name: "Oak Hall Expeditions",
    website: "https://www.oakhall.co.uk/",
    category: "tours",
    subCategory: "Activity / Adventure",
    location: "Otford, Kent",
    description:
      "Affordable community-focused Christian holidays including ski trips, summer expeditions and adventure travel with Bible teaching and fellowship.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Bible sessions", "Affordable pricing", "Community focus", "Adventure travel"],
    tags: ["Interdenominational", "Adventure", "Young Adults"],
    targetAudience: "Young adults, Families, Groups",
    featured: true,
  },
  {
    id: "TO003",
    name: "McCabe Pilgrimages",
    website: "https://www.mccabe-travel.co.uk/",
    category: "pilgrimages",
    subCategory: "Pilgrimage",
    location: "UK",
    description:
      "UK's leading operator of tours and pilgrimages to the Holy Land and other biblical and historical sites. Also offers fellowship tours.",
    denominationFocus: "Anglican / Interdenominational",
    keyFeatures: ["Expert guides", "Holy Land specialists", "Fellowship tours", "Cultural immersion"],
    tags: ["Anglican", "Holy Land", "Pilgrimage"],
    targetAudience: "Church groups, Individuals, Couples",
    featured: true,
  },
  {
    id: "TO004",
    name: "Tangney Tours",
    website: "https://www.tangney-tours.com/",
    category: "pilgrimages",
    subCategory: "Catholic Pilgrimage",
    location: "UK",
    description:
      "UK's leading Catholic pilgrimage operator specialising in group pilgrimages to Lourdes, Fatima, Rome, the Holy Land and other major Catholic shrines.",
    denominationFocus: "Catholic",
    keyFeatures: ["Lourdes specialists", "Assisted pilgrimage", "Group organisers travel free"],
    tags: ["Catholic", "Lourdes", "Rome", "Holy Land"],
    targetAudience: "Catholic parishes, Groups, Individuals",
    featured: true,
  },
  {
    id: "TO005",
    name: "Inspiration Travel",
    website: "https://www.inspiration-travel.co.uk/",
    category: "tours",
    subCategory: "Coach Tours",
    location: "UK",
    description:
      "A well-established Christian coach tour operator offering European holidays and UK breaks with a strong community ethos and a programme of optional Christian activities.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Coach tours", "European breaks", "Community ethos", "Optional Christian programme"],
    tags: ["Interdenominational", "Coach", "Europe"],
    targetAudience: "Seniors, Couples, Individuals",
  },
  {
    id: "TO006",
    name: "Holy Land Experience Tours",
    website: "https://www.holyland-tours.co.uk/",
    category: "pilgrimages",
    subCategory: "Pilgrimage",
    location: "UK",
    description:
      "Specialist tours to Israel and the Holy Land, offering tailored group pilgrimages with expert Christian guides and flexible itineraries.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Holy Land specialists", "Tailored itineraries", "Expert Christian guides"],
    tags: ["Interdenominational", "Holy Land", "Israel"],
    targetAudience: "Church groups, Individuals",
  },
  {
    id: "TO025",
    name: "All Saints Travel",
    website: "https://www.allsaintstravel.co.uk/",
    category: "pilgrimages",
    subCategory: "Pilgrimage",
    location: "UK",
    description: "Specialises in Christian pilgrimages for groups wanting to travel the world. Unique expertise in South Korea and SE Asia pilgrimages.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["South Korea/SE Asia specialism", "Bespoke group itineraries"],
    tags: ["Interdenominational", "Pilgrimage"],
    targetAudience: "Church groups, Clergy",
  },
  {
    id: "TO026",
    name: "Christian Fellowship Tours",
    website: "https://www.christianfellowshiptours.com/",
    category: "pilgrimages",
    subCategory: "Pilgrimage / Heritage",
    location: "UK",
    description: "Offers guided pilgrimage tours including UK Celtic pilgrimages exploring early Christian missionaries and saints.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Celtic pilgrimage specialism", "Heritage focus"],
    tags: ["Interdenominational", "Pilgrimage"],
    targetAudience: "History enthusiasts, Church groups",
  },
  {
    id: "TO007",
    name: "Worldwide Christian Travel",
    website: "https://www.worldwidechristiantravel.com/",
    category: "pilgrimages",
    subCategory: "Pilgrimage / Tours",
    location: "Bristol, UK",
    description: "Organises group tours and pilgrimages worldwide. Long-established Bristol-based operator (Company No. 02314005).",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Group tour specialists", "Wide destination range"],
    tags: ["Interdenominational", "Pilgrimage"],
    targetAudience: "Church groups, Individuals",
  },
  {
    id: "TO008",
    name: "Sonas Christian Holidays",
    website: "https://sonaschristianholidays.com/",
    category: "tours",
    subCategory: "Leisure / Beach",
    location: "Scottish Highlands, UK",
    description: "Faith-based holiday company offering membership plans for Christians interested in group holidays with a spiritual dimension.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Membership model", "Scottish Highlands base"],
    tags: ["Interdenominational", "Leisure"],
    targetAudience: "Families, Couples, Singles",
  },
  {
    id: "TO009",
    name: "Gold Hill Holidays",
    website: "https://goldhillholidays.co.uk/",
    category: "tours",
    subCategory: "Activity / Ski",
    location: "UK",
    description: "Christian holiday organisation providing fun, outdoor, affordable and exciting holidays for over thirty years. Skiing and activity holidays.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Ski holidays", "Mountain huts", "Via Ferrata", "Daily worship and Bible teaching"],
    tags: ["Interdenominational", "Activity"],
    targetAudience: "Young adults, Families, Active travellers",
  },
  {
    id: "TO010",
    name: "JC Journeys",
    website: "https://www.jcjourneys.com/",
    category: "pilgrimages",
    subCategory: "Pilgrimage / Heritage",
    location: "UK",
    description: "Christian travel company offering guided pilgrimages and heritage tours to biblical lands.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Biblical heritage focus", "Guided tours"],
    tags: ["Interdenominational", "Pilgrimage"],
    targetAudience: "Church groups, Individuals",
  },
  {
    id: "TO011",
    name: "Journeying",
    website: "https://www.journeying.co.uk/",
    category: "tours",
    subCategory: "Walking Holidays",
    location: "UK",
    description: "Takes small groups of up to 10 people on guided walking tour holidays in an informal Christian ambience to off-the-beaten-track destinations.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Small group max 10", "Off-the-beaten-track", "Informal Christian ambience"],
    tags: ["Interdenominational", "Walking Holidays"],
    targetAudience: "Walkers, Small groups, Active travellers",
  },
  {
    id: "TO012",
    name: "Spring Harvest Holidays",
    website: "https://springharvestholidays.com/",
    category: "tours",
    subCategory: "Family / Beach",
    location: "UK",
    description: "Independent company (part of Essential Christian family) offering family holiday park experiences in France with Christian programming.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Holiday park", "Swimming pools", "Kids clubs", "Accessible mobile homes"],
    tags: ["Interdenominational", "Family"],
    targetAudience: "Families with children",
  },
  {
    id: "TO013",
    name: "Aglow Pilgrimages",
    website: "https://www.aglowpilgrimages.com/",
    category: "pilgrimages",
    subCategory: "Pilgrimage",
    location: "UK",
    description: "Pilgrimage operator offering group trips to major Christian shrines with flights from regional UK airports.",
    denominationFocus: "Catholic",
    keyFeatures: ["Regional UK departures", "Assisted pilgrimages"],
    tags: ["Catholic", "Pilgrimage"],
    targetAudience: "Catholic parishes, Groups",
  },
  {
    id: "TO014",
    name: "Norman Allen Group Travel",
    website: "https://www.normanallen.co.uk/",
    category: "tours",
    subCategory: "Group Travel",
    location: "UK",
    description: "Specialist in organising group travel for churches, choirs, and Christian organisations.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Bespoke group itineraries", "Church group specialists"],
    tags: ["Interdenominational", "Group Travel"],
    targetAudience: "Church groups, Choirs, Organisations",
  },
  {
    id: "TO015",
    name: "Pilgrims and Prophets Tours",
    website: "https://www.pilgrimsandprophets.co.uk/",
    category: "tours",
    subCategory: "Heritage Tours",
    location: "UK",
    description: "Offers Christian heritage tours within the UK, exploring sites connected to revival history, missionaries, and church history.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["UK Christian heritage specialism", "Free travel advice"],
    tags: ["Interdenominational", "Heritage Tours"],
    targetAudience: "Heritage tourists, International visitors to UK",
    contactPhone: "+44 7470 366689",
  },
  {
    id: "TO016",
    name: "Christian Cruises UK",
    website: "https://christian-cruises.co.uk/",
    category: "tours",
    subCategory: "Cruise",
    location: "UK",
    description: "Specialises in creating quality cruises with a Christian theme whether in the UK or around the world.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Themed Christian cruises", "UK and international sailings"],
    tags: ["Interdenominational", "Cruise"],
    targetAudience: "Couples, Singles, Groups",
  },
  {
    id: "TO017",
    name: "Inspiration Cruises & Tours",
    website: "https://www.inspirationtravel.com/",
    category: "tours",
    subCategory: "Cruise",
    location: "UK/International",
    description: "Faith-based cruise vacations featuring Christian speakers, musicians, and comedians on major cruise lines.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Celebrity Christian speakers", "Major cruise lines", "Music-themed cruises"],
    tags: ["Interdenominational", "Cruise"],
    targetAudience: "Couples, Families, Groups",
    featured: true,
  },
  {
    id: "TO018",
    name: "Christian Holiday People",
    website: "https://www.christianholidays.co.uk/",
    category: "tours",
    subCategory: "Domestic Holidays",
    location: "UK",
    description: "UK holiday centres with several breaks each year designed specifically for singles and groups.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Singles-specific breaks", "UK-based"],
    tags: ["Interdenominational", "Domestic Holidays"],
    targetAudience: "Singles, Groups",
  },
  {
    id: "TO019",
    name: "Travelink / Tours for Christians",
    website: "https://www.toursforchristians.co.uk/",
    category: "pilgrimages",
    subCategory: "Pilgrimage / Tours",
    location: "UK",
    description: "Offers a range of Christian tours and pilgrimages for groups and individuals.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Group and individual tours"],
    tags: ["Interdenominational", "Pilgrimage"],
    targetAudience: "Church groups, Individuals",
  },
  {
    id: "TO020",
    name: "Globus",
    website: "https://www.globusjourneys.co.uk/tour/religious/",
    category: "tours",
    subCategory: "Escorted Tours",
    location: "UK/International",
    description: "Escorted religious tours to Israel Jordan Egypt and Europe",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Expert guides", "Faith-based itineraries"],
    tags: ["Interdenominational", "Escorted Tours"],
    targetAudience: "Couples, Groups",
    featured: true,
  },
  {
    id: "TO021",
    name: "Trafalgar",
    website: "https://www.trafalgar.com/real-word/christian-tours/",
    category: "tours",
    subCategory: "Escorted Tours",
    location: "UK/International",
    description: "Guided tours covering Christian history like Martin Luther Reformation",
    denominationFocus: "Interdenominational",
    keyFeatures: ["History focus", "Expert guides"],
    tags: ["Interdenominational", "Escorted Tours"],
    targetAudience: "Couples, Groups",
  },
  {
    id: "TO022",
    name: "Lightline Pilgrimages",
    website: "https://www.lightline.org.uk/",
    category: "pilgrimages",
    subCategory: "Pilgrimage",
    location: "UK",
    description: "UK-based operator focusing on supporting local Christians in the Holy Land",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Supports Living Stones", "Christian-owned partners"],
    tags: ["Interdenominational", "Pilgrimage"],
    targetAudience: "Church groups, Individuals",
    featured: true,
  },
  {
    id: "TO023",
    name: "UTracks",
    website: "https://www.utracks.com/Camino/Camino-de-Santiago",
    category: "tours",
    subCategory: "Walking Tours",
    location: "UK/International",
    description: "Guided and self-guided Camino de Santiago tours",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Camino specialists", "Self-guided options"],
    tags: ["Interdenominational", "Walking Tours"],
    targetAudience: "Walkers, Pilgrims",
    featured: true,
  },
  {
    id: "TO024",
    name: "Titan Travel",
    website: "https://www.titantravel.co.uk/",
    category: "tours",
    subCategory: "Escorted Tours",
    location: "UK",
    description: "Packages for the Oberammergau Passion Play",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Oberammergau packages", "Escorted travel"],
    tags: ["Interdenominational", "Escorted Tours"],
    targetAudience: "Groups, Individuals",
  },
];

/** Featured retreats & accommodation */
export const RETREATS: Provider[] = [
{
    id: "RA001",
    name: "Lee Abbey Devon",
    website: "https://leeabbeydevon.org.uk/",
    category: "retreats",
    subCategory: "Conference / Retreat",
    location: "Lynton, Devon",
    region: "South West",
    country: "UK",
    description:
      "Retreat and conference centre in North Devon run by an international Christian community. Offers themed weeks, outdoor/walking holidays, and a community living experience.",
    denominationFocus: "Anglican / Interdenominational",
    keyFeatures: ["International community", "Coastal location", "Walking weeks", "Youth programmes"],
    tags: ["Anglican", "Coastal", "Walking", "Community"],
    accessibility: "Partial",
    contactEmail: "bookings@leeabbey.org.uk",
    contactPhone: "01598 752621",
    featured: true,
  },
  {
    id: "RA002",
    name: "Capernwray Hall",
    website: "https://capernwray.org/holidays/",
    category: "retreats",
    subCategory: "Holiday Centre",
    location: "Carnforth, Lancashire",
    region: "North West",
    country: "UK",
    description:
      "Christ-centred holiday centre in stunning Lancashire countryside near the Lake District and Yorkshire Dales.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Bible teaching", "Beautiful grounds", "Near Lake District", "Seasonal holidays"],
    tags: ["Interdenominational", "Lake District", "Bible Teaching"],
    featured: true,
  },
  {
    id: "RA003",
    name: "CEHC Beechwood Court",
    website: "https://www.cehc.org.uk/",
    category: "retreats",
    subCategory: "Holiday Centre",
    location: "Conwy, North Wales",
    region: "Wales",
    country: "UK",
    description:
      "Holiday centre on the North Wales coast offering themed weeks, family holidays, and seniors breaks, including a Holiday Support Fund for those needing financial help.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Seniors programme", "Holiday Support Fund", "Themed weeks", "North Wales coast"],
    tags: ["Interdenominational", "Seniors", "Wales", "Family"],
    contactPhone: "01492 593405",
    featured: true,
  },
  {
    id: "RA005",
    name: "The Wellspring Ledbury",
    website: "https://www.thewellspring.uk/",
    category: "retreats",
    subCategory: "Day Retreat / Events",
    location: "Ledbury, Herefordshire",
    region: "West Midlands",
    country: "UK",
    description:
      "Christian day retreat and events centre on the southern edge of the Malvern Hills AONB. Also offers Wellspring Cottage for self-catering retreats.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Malvern Hills AONB", "Day retreats", "Self-catering cottage", "Events"],
    tags: ["Interdenominational", "AONB", "Self-catering"],
    contactEmail: "info@thewellspring.uk",
    contactPhone: "01531 635727",
    featured: true,
  },
  {
    id: "RA006",
    name: "Scargill House",
    website: "https://www.scargillmovement.org/",
    category: "retreats",
    subCategory: "Conference / Retreat",
    location: "Skipton, North Yorkshire",
    region: "Yorkshire",
    country: "UK",
    description:
      "Christian retreat and conference centre in the Yorkshire Dales offering themed breaks, community living, and quiet days.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Yorkshire Dales", "Community living", "Themed breaks", "Quiet days"],
    tags: ["Interdenominational", "Yorkshire Dales", "Retreat"],
  },
  {
    id: "RA007",
    name: "Ashburnham Place",
    website: "https://www.ashburnham.org.uk/",
    category: "retreats",
    subCategory: "Conference / Retreat",
    location: "Battle, East Sussex",
    region: "South East",
    country: "UK",
    description:
      "Christian conference and retreat centre set in 220 acres of parkland and gardens in East Sussex.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["220 acres", "Conference facilities", "Prayer ministry"],
    tags: ["Interdenominational", "East Sussex", "Conference"],
  },
  {
    id: "RA009",
    name: "Ampleforth Abbey",
    website: "https://www.ampleforth.org.uk/",
    category: "retreats",
    subCategory: "Monastery",
    location: "York, North Yorkshire",
    region: "Yorkshire",
    country: "UK",
    description:
      "Benedictine monastery offering hospitality and retreats for individuals and groups seeking peace and prayer.",
    denominationFocus: "Catholic / Benedictine",
    keyFeatures: ["Benedictine community", "Historic monastery", "Peaceful setting"],
    tags: ["Catholic", "Benedictine", "Monastery"],
  },
  {
    id: "RA004",
    name: "Christian Endeavour Holiday Centres (The Pleasaunce)",
    website: "https://www.cehc.org.uk/",
    category: "retreats",
    subCategory: "Catered Holidays",
    location: "Overstrand, Norfolk",
    region: "East of England",
    country: "UK",
    description: "Holiday centre in Norfolk offering themed weeks, family holidays, and seniors breaks with full board accommodation.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Seniors programme", "Norfolk coast", "Full board", "Themed weeks"],
    tags: ["Interdenominational", "Catered Holidays"],
  },
  {
    id: "RA008",
    name: "Launde Abbey",
    website: "https://www.launde.org.uk/",
    category: "retreats",
    subCategory: "Retreat House",
    location: "East Norton, Leicestershire",
    region: "East Midlands",
    country: "UK",
    description: "Anglican retreat house offering guided and individually guided retreats, quiet days, and conference facilities.",
    denominationFocus: "Anglican / Interdenominational",
    keyFeatures: ["Historic building", "Guided retreats", "Quiet days"],
    tags: ["Anglican", "Interdenominational", "Retreat House"],
    featured: true,
  },
  {
    id: "RA010",
    name: "Worth Abbey",
    website: "https://www.worthabbey.net/",
    category: "retreats",
    subCategory: "Monastery",
    location: "Crawley, West Sussex",
    region: "South East",
    country: "UK",
    description: "Catholic Benedictine monastery offering retreats, quiet days, and spiritual direction in West Sussex.",
    denominationFocus: "Catholic / Benedictine",
    keyFeatures: ["Benedictine community", "Open Cloister programme"],
    tags: ["Catholic", "Benedictine", "Monastery"],
    featured: true,
  },
  {
    id: "RA011",
    name: "Buckfast Abbey",
    website: "https://www.buckfast.org.uk/",
    category: "retreats",
    subCategory: "Monastery",
    location: "Buckfastleigh, Devon",
    region: "South West",
    country: "UK",
    description: "Working Benedictine monastery in Devon offering retreat accommodation and spiritual programmes.",
    denominationFocus: "Catholic / Benedictine",
    keyFeatures: ["Working monastery", "Devon location", "Gift shop and grounds"],
    tags: ["Catholic", "Benedictine", "Monastery"],
  },
  {
    id: "RA012",
    name: "Douai Abbey",
    website: "https://www.douaiabbey.org.uk/",
    category: "retreats",
    subCategory: "Monastery",
    location: "Reading, Berkshire",
    region: "South East",
    country: "UK",
    description: "Benedictine monastery offering retreat accommodation and hospitality.",
    denominationFocus: "Catholic / Benedictine",
    keyFeatures: ["Benedictine community", "Peaceful setting"],
    tags: ["Catholic", "Benedictine", "Monastery"],
  },
  {
    id: "RA013",
    name: "Foxhill",
    website: "https://www.foxhillconferences.co.uk/",
    category: "retreats",
    subCategory: "Conference / Retreat",
    location: "Frodsham, Cheshire",
    region: "North West",
    country: "UK",
    description: "Anglican conference and retreat centre in Cheshire.",
    denominationFocus: "Anglican / Interdenominational",
    keyFeatures: ["Conference facilities", "Cheshire countryside"],
    tags: ["Anglican", "Interdenominational", "Conference"],
  },
  {
    id: "RA014",
    name: "Parcevall Hall",
    website: "https://www.parcevall.bradford.anglican.org/",
    category: "retreats",
    subCategory: "Retreat House",
    location: "Appletreewick, North Yorkshire",
    region: "Yorkshire",
    country: "UK",
    description: "Anglican retreat house in the Yorkshire Dales offering quiet days and group retreats.",
    denominationFocus: "Anglican / Interdenominational",
    keyFeatures: ["Yorkshire Dales", "Beautiful gardens"],
    tags: ["Anglican", "Interdenominational", "Retreat House"],
  },
  {
    id: "RA015",
    name: "Wydale Hall",
    website: "https://www.wydale.org/",
    category: "retreats",
    subCategory: "Conference / Retreat",
    location: "Brompton-by-Sawdon, North Yorkshire",
    region: "Yorkshire",
    country: "UK",
    description: "Anglican conference and retreat centre near Scarborough offering retreats, conferences, and quiet days.",
    denominationFocus: "Anglican / Interdenominational",
    keyFeatures: ["Near Scarborough", "Conference facilities"],
    tags: ["Anglican", "Interdenominational", "Conference"],
  },
  {
    id: "RA016",
    name: "Sheldon (Society of Mary and Martha)",
    website: "https://www.sheldonretreat.com/",
    category: "retreats",
    subCategory: "Clergy Retreat",
    location: "Doddiscombsleigh, Devon",
    region: "South West",
    country: "UK",
    description: "Retreat centre specifically supporting clergy and church leaders with rest, reflection, and renewal.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Clergy-specific", "Burnout support", "Devon countryside"],
    tags: ["Interdenominational", "Clergy Retreat"],
  },
  {
    id: "RA017",
    name: "Sarum College",
    website: "https://www.sarum.ac.uk/",
    category: "retreats",
    subCategory: "Academic / Retreat",
    location: "Salisbury, Wiltshire",
    region: "South West",
    country: "UK",
    description: "Ecumenical theological college in Salisbury Cathedral Close offering courses, retreats, and accommodation.",
    denominationFocus: "Ecumenical",
    keyFeatures: ["Cathedral Close location", "Academic programmes", "Retreats"],
    tags: ["Ecumenical", "Academic"],
  },
  {
    id: "RA018",
    name: "Greenhouse Christian Centre",
    website: "https://www.the-greenhouse.org/",
    category: "retreats",
    subCategory: "Guest House / Retreat",
    location: "Poole, Dorset",
    region: "South West",
    country: "UK",
    description: "Free Church Christian guest house and retreat centre near Bournemouth offering B&B and full-board accommodation.",
    denominationFocus: "Free Church / Interdenominational",
    keyFeatures: ["Near Bournemouth", "B&B and full board", "Quiet days"],
    tags: ["Free Church", "Interdenominational", "Guest House"],
  },
  {
    id: "RA019",
    name: "Crowhurst Christian Healing Centre",
    website: "https://www.crowhursthealing.co.uk/",
    category: "retreats",
    subCategory: "Healing / Retreat",
    location: "Battle, East Sussex",
    region: "South East",
    country: "UK",
    description: "Anglican healing centre offering retreats focused on Christian healing ministry.",
    denominationFocus: "Anglican / Interdenominational",
    keyFeatures: ["Healing ministry", "Quiet retreats"],
    tags: ["Anglican", "Interdenominational", "Healing"],
  },
  {
    id: "RA020",
    name: "Letton Hall",
    website: "https://www.lettonhall.org/",
    category: "retreats",
    subCategory: "Conference / Activity",
    location: "Shipdham, Norfolk",
    region: "East of England",
    country: "UK",
    description: "Christian conference and activity centre in Norfolk offering group bookings and holiday weeks.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Activity centre", "Group bookings", "Norfolk"],
    tags: ["Interdenominational", "Conference"],
  },
  {
    id: "RA021",
    name: "Othona Community (Bradwell)",
    website: "https://www.othona-bb.org.uk/",
    category: "retreats",
    subCategory: "Community / Retreat",
    location: "Bridport, Dorset",
    region: "South West",
    country: "UK",
    description: "Interdenominational Christian community offering retreats, holidays, and community living experiences.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Community living", "Simple accommodation", "Eco-focus"],
    tags: ["Interdenominational", "Community"],
  },
  {
    id: "RA022",
    name: "Minsteracres Retreat Centre",
    website: "https://www.minsteracres.org/",
    category: "retreats",
    subCategory: "Retreat House",
    location: "Consett, County Durham",
    region: "North East",
    country: "UK",
    description: "Passionist-run retreat centre with 110 acres of land welcoming individuals for private retreats and guided programmes.",
    denominationFocus: "Catholic / Interdenominational",
    keyFeatures: ["110 acres", "Passionist community", "North East"],
    tags: ["Catholic", "Interdenominational", "Retreat House"],
  },
  {
    id: "RA023",
    name: "Shepherds Dene",
    website: "https://www.shepherdsdene.co.uk/",
    category: "retreats",
    subCategory: "Retreat House",
    location: "Riding Mill, Northumberland",
    region: "North East",
    country: "UK",
    description: "Anglican retreat house in Northumberland offering quiet days, guided retreats, and group bookings.",
    denominationFocus: "Anglican / Interdenominational",
    keyFeatures: ["Northumberland countryside", "Quiet setting"],
    tags: ["Anglican", "Interdenominational", "Retreat House"],
  },
  {
    id: "RA024",
    name: "Ffald-y-Brenin",
    website: "https://www.ffald-y-brenin.org/",
    category: "retreats",
    subCategory: "Prayer / Retreat",
    location: "Fishguard, Pembrokeshire",
    region: "Wales",
    country: "UK",
    description: "Christian retreat centre in Pembrokeshire known for its prayer ministry and peaceful setting in the Welsh hills.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Prayer ministry", "Welsh hills", "Peaceful setting"],
    tags: ["Interdenominational", "Prayer"],
  },
  {
    id: "RA025",
    name: "Thornleigh Hotel",
    website: "https://www.thornleighhotel.co.uk/",
    category: "retreats",
    subCategory: "Christian Hotel",
    location: "Grange-over-Sands, Cumbria",
    region: "North West",
    country: "UK",
    description: "Christian-run hotel in the Lake District offering comfortable accommodation with a Christian ethos.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Lake District location", "Christian ethos", "Hotel standard"],
    tags: ["Interdenominational", "Christian Hotel"],
  },
  {
    id: "RA026",
    name: "The Royal Foundation of St Katharine",
    website: "https://rfsk.org.uk/",
    category: "retreats",
    subCategory: "Retreat / Conference",
    location: "Limehouse, London",
    region: "London",
    country: "UK",
    description: "Anglican retreat and conference centre in East London offering quiet days, retreats, and meeting spaces.",
    denominationFocus: "Anglican / Interdenominational",
    keyFeatures: ["Central London", "Historic foundation"],
    tags: ["Anglican", "Interdenominational", "Retreat"],
  },
  {
    id: "RA027",
    name: "Marygate House",
    website: "https://www.marygatehouse.org.uk/",
    category: "retreats",
    subCategory: "Retreat House",
    location: "Holy Island, Northumberland",
    region: "North East",
    country: "UK",
    description: "Retreat house on Holy Island (Lindisfarne) offering accommodation for individuals and small groups on retreat.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Holy Island location", "Pilgrimage base"],
    tags: ["Interdenominational", "Retreat House"],
  },
  {
    id: "RA028",
    name: "Community of Aidan and Hilda",
    website: "https://www.aidanandhilda.org.uk/",
    category: "retreats",
    subCategory: "Community / Retreat",
    location: "Holy Island, Northumberland",
    region: "North East",
    country: "UK",
    description: "Dispersed Celtic-inspired Christian community based on Holy Island offering retreats and pilgrimage experiences.",
    denominationFocus: "Interdenominational / Celtic",
    keyFeatures: ["Celtic spirituality", "Holy Island", "Pilgrimage"],
    tags: ["Interdenominational", "Celtic", "Community"],
  },
  {
    id: "RA029",
    name: "Wykes Manor",
    website: "https://www.wykesmanor.com/",
    category: "retreats",
    subCategory: "Country House / Retreat",
    location: "Lincolnshire",
    region: "East Midlands",
    country: "UK",
    description: "Ancient Fenland manor offering retreat accommodation and country house guesthouse experience.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Historic manor", "Lincolnshire", "Unique setting"],
    tags: ["Interdenominational", "Country House"],
  },
  {
    id: "RA030",
    name: "L'Abri Fellowship (England)",
    website: "https://www.labri.org/england/",
    category: "retreats",
    subCategory: "Study Centre",
    location: "Greatham, Hampshire",
    region: "South East",
    country: "UK",
    description: "International Christian study centre offering residential study programmes exploring faith and culture.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Study programmes", "Intellectual engagement", "Community"],
    tags: ["Interdenominational", "Study Centre"],
  },
  {
    id: "RA031",
    name: "Champing (The Churches Conservation Trust)",
    website: "https://champing.co.uk/",
    category: "retreats",
    subCategory: "Church Camping",
    location: "Various",
    region: "UK",
    country: "UK",
    description: "Unique concept of camping overnight in historic churches across the UK.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Exclusive use", "Historic buildings", "Dog friendly"],
    tags: ["Interdenominational", "Church Camping"],
    contactEmail: "champing@thecct.org.uk",
    contactPhone: "0207 841 0436",
    featured: true,
  },
  {
    id: "RA032",
    name: "Quiet Waters",
    website: "https://www.quietwaters.org.uk/",
    category: "retreats",
    subCategory: "Creative Retreat",
    location: "Suffolk",
    region: "East of England",
    country: "UK",
    description: "Christian retreat house offering led retreats, creative workshops, and peaceful surroundings.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Creative workshops", "Led retreats", "Peaceful setting"],
    tags: ["Interdenominational", "Creative Retreat"],
  },
  {
    id: "RA033",
    name: "Christian Conference Trust (The Hayes)",
    website: "https://www.cct.org.uk/conferences/exclusive-use",
    category: "retreats",
    subCategory: "Conference / Retreat",
    location: "Swanwick",
    region: "East Midlands",
    country: "UK",
    description: "Large conference centre offering exclusive use for Christian groups up to 400 guests.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Exclusive use", "26 meeting spaces", "All-inclusive packages"],
    tags: ["Interdenominational", "Conference"],
    contactEmail: "info@cct.org.uk",
    contactPhone: "0300 111 4444",
  },
  {
    id: "RA034",
    name: "Christian Conference Trust (High Leigh)",
    website: "https://www.cct.org.uk/conferences/exclusive-use",
    category: "retreats",
    subCategory: "Conference / Retreat",
    location: "Hoddesdon",
    region: "East of England",
    country: "UK",
    description: "Large conference centre near London catering for up to 320 guests.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Exclusive use", "21 meeting spaces", "All-inclusive packages"],
    tags: ["Interdenominational", "Conference"],
    contactEmail: "info@cct.org.uk",
    contactPhone: "0300 111 4444",
  },
  {
    id: "RA035",
    name: "Christian Conference Trust (Highgate House)",
    website: "https://www.cct.org.uk/conferences/exclusive-use",
    category: "retreats",
    subCategory: "Conference / Retreat",
    location: "Creaton",
    region: "East Midlands",
    country: "UK",
    description: "Stunning Northamptonshire conference centre perfect for exclusive use for Christian groups of up to 160 adults.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Exclusive use", "16 meeting spaces", "All-inclusive packages"],
    tags: ["Interdenominational", "Conference"],
    contactEmail: "info@cct.org.uk",
    contactPhone: "0300 111 4444",
  },
  {
    id: "RA036",
    name: "Bassenfell Manor Christian Centre",
    website: "https://www.bassenfell.org.uk/",
    category: "retreats",
    subCategory: "Activity / Holiday Centre",
    location: "Keswick",
    region: "North West",
    country: "UK",
    description: "Victorian manor house offering activity holidays, walking weeks, and catered holidays with Christian fellowship.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Lake District", "Walking weeks", "En-suite rooms", "Special diets catered"],
    tags: ["Interdenominational", "Activity"],
  },
  {
    id: "RA037",
    name: "Cefn Lea",
    website: "https://www.cefnlea.co.uk/",
    category: "retreats",
    subCategory: "Holiday Park / Conference",
    location: "Mid Wales",
    region: "Wales",
    country: "UK",
    description: "Christian conference and holiday park in the heart of Mid Wales.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Holiday park", "Conference facilities", "Mid Wales location"],
    tags: ["Interdenominational", "Holiday Park"],
    contactPhone: "01686 625275",
    featured: true,
  },
  {
    id: "RA038",
    name: "Stanton House",
    website: "https://www.stantonhouse.org.uk/",
    category: "retreats",
    subCategory: "Retreat House",
    location: "Oxford",
    region: "South East",
    country: "UK",
    description: "Idyllic and peaceful Christian retreat house set in beautiful grounds in Oxford.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Peaceful grounds", "Quiet days", "Group retreats"],
    tags: ["Interdenominational", "Retreat House"],
  },
  {
    id: "RA039",
    name: "Waverley Abbey",
    website: "https://www.waverleyabbey.org/events-and-hospitality/retreats/",
    category: "retreats",
    subCategory: "Retreat House",
    location: "Farnham",
    region: "South East",
    country: "UK",
    description: "Christian retreats, workshops, and worship nights set in historic abbey grounds.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Historic abbey", "Workshops", "Worship nights"],
    tags: ["Interdenominational", "Retreat House"],
  },
  {
    id: "RA040",
    name: "Harker Grange",
    website: "https://www.harkergrange.co.uk/",
    category: "retreats",
    subCategory: "Marriage / Couples Retreat",
    location: "Carlisle",
    region: "North West",
    country: "UK",
    description: "Christian retreat centre in Cumbria specifically supporting marriages through retreat weekend ministry.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Marriage support", "Couples retreats", "Cumbria"],
    tags: ["Interdenominational", "Marriage"],
  },
];

/** Youth & activity camps */
export const YOUTH_CAMPS: Provider[] = [
{
    id: "YA001",
    name: "Scripture Union Holidays",
    website: "https://www.scriptureunion.org.uk/",
    category: "youth",
    subCategory: "Residential Holidays",
    location: "Various UK locations",
    description:
      "A great range of Christian holidays each Summer and Easter for children and young people aged 8–18.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Residential camps", "Beach missions", "Outdoor activities", "Faith programmes"],
    tags: ["Interdenominational", "Children", "Summer"],
    ageRange: "8–18",
    featured: true,
  },
  {
    id: "YA002",
    name: "CPAS Ventures",
    website: "https://www.cpas.org.uk/ventures",
    category: "youth",
    subCategory: "Adventure Camps",
    location: "Various UK locations",
    description:
      "Christian adventure camps for young people combining outdoor activities with Bible teaching and Christian community.",
    denominationFocus: "Anglican",
    keyFeatures: ["Adventure activities", "Bible teaching", "Team building"],
    tags: ["Anglican", "Adventure", "Teens"],
    ageRange: "11–18",
    featured: true,
  },
  {
    id: "YA003",
    name: "Rock UK",
    website: "https://www.rockuk.org/",
    category: "youth",
    subCategory: "Outdoor Adventure",
    location: "Multiple UK centres",
    description:
      "Christian outdoor education and activity centre charity offering residential and day visits to a wide range of groups.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Outdoor education", "Activity centres", "Group bookings", "Residential visits"],
    tags: ["Interdenominational", "Outdoor", "Groups"],
    ageRange: "5+",
  },
  {
    id: "YA004",
    name: "Through the Roof",
    website: "https://www.throughtheroof.org/",
    category: "youth",
    subCategory: "Accessible Holidays",
    location: "UK",
    description:
      "Charity organising full-board accessible holidays combining Christian worship with tailored support for disabled individuals.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Accessible facilities", "Tailored support", "Christian worship", "Full board"],
    tags: ["Interdenominational", "Accessible", "Disabled"],
    accessibility: "Full",
  },
  {
    id: "YA021",
    name: "Abernethy Trust",
    website: "https://www.abernethy.org.uk/",
    category: "youth",
    subCategory: "Outdoor Adventure",
    location: "Nethy Bridge, Scotland",
    description: "Provides adventure residential experiences through outdoor adventure centres in wild locations across Scotland.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Hillwalking", "Kayaking", "Rock climbing", "Gorge walking", "Skiing"],
    tags: ["Interdenominational", "Outdoor Adventure"],
    ageRange: "All ages",
    contactEmail: "[email protected]",
    contactPhone: "01479 818 001",
  },
  {
    id: "YA005",
    name: "West Runton Holidays",
    website: "https://www.westrunton.org.uk/",
    category: "youth",
    subCategory: "Activity Holidays",
    location: "West Runton, Norfolk",
    description: "Christian activity holidays for young people combining outdoor adventure with Bible teaching and worship.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Surfing", "Climbing", "Archery", "Bushcraft", "Bible teaching"],
    tags: ["Interdenominational", "Activity Holidays"],
    ageRange: "8-18",
    featured: true,
  },
  {
    id: "YA006",
    name: "Min-y-Don Christian Adventure Centre",
    website: "https://minydon.com/",
    category: "youth",
    subCategory: "Outdoor Adventure",
    location: "Arthog, Wales",
    description: "Christian adventure centre in Wales offering a wide range of outdoor activities for youth groups and families.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Archery", "Bushcraft", "Canoeing", "High ropes", "Rock climbing", "Kayaking"],
    tags: ["Interdenominational", "Outdoor Adventure"],
    ageRange: "All ages",
  },
  {
    id: "YA007",
    name: "Viney Hill Christian Adventure Centre",
    website: "https://www.vineyhilladventure.org/",
    category: "youth",
    subCategory: "Outdoor Adventure",
    location: "Forest of Dean, Gloucestershire",
    description: "Christian adventure centre in the Forest of Dean offering outdoor programmes for youth groups.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Climbing", "Archery", "Bushcraft", "Canoeing", "Problem solving"],
    tags: ["Interdenominational", "Outdoor Adventure"],
    ageRange: "All ages",
  },
  {
    id: "YA008",
    name: "CCiW (Christian Camps in Wales)",
    website: "https://www.cciw.co.uk/",
    category: "youth",
    subCategory: "Outdoor Camps",
    location: "Various sites, Wales",
    description: "Charitable company running outdoor camps on multiple sites in Wales with God and the Bible at the centre of each day.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Outdoor camping", "Bible teaching", "Adventure activities", "Fellowship"],
    tags: ["Interdenominational", "Outdoor Camps"],
    ageRange: "10-18",
  },
  {
    id: "YA009",
    name: "Free Church Youth Camps",
    website: "https://www.freechurchyouthcamps.org/",
    category: "youth",
    subCategory: "Residential Holidays",
    location: "Various UK locations",
    description: "Week-long fun-packed Christian residential holidays for young people aged 10-18. Everyone welcome.",
    denominationFocus: "Free Church / Interdenominational",
    keyFeatures: ["Activities", "Bible teaching", "Worship", "Games", "Fellowship"],
    tags: ["Free Church", "Interdenominational", "Residential Holidays"],
    ageRange: "10-18",
  },
  {
    id: "YA010",
    name: "New Church Camps",
    website: "https://newchurchcamps.org.uk/",
    category: "youth",
    subCategory: "Residential / Family",
    location: "Various UK locations",
    description: "Camps for young people aged 9+ in locations around the UK. Also offers weekends for families of all ages and sizes.",
    denominationFocus: "New Church / Interdenominational",
    keyFeatures: ["Activities", "Bible teaching", "Family weekends"],
    tags: ["New Church", "Interdenominational", "Residential"],
    ageRange: "9+",
  },
  {
    id: "YA011",
    name: "TeenStreet UK",
    website: "https://teenstreet.uk/",
    category: "youth",
    subCategory: "Residential Event",
    location: "Carnforth, Lancashire",
    description: "Christian youth event for teens aged 13-17. Action-packed week of teaching, small group time, worship, workshops, sports.",
    denominationFocus: "Interdenominational (Operation Mobilisation)",
    keyFeatures: ["Teaching", "Small groups", "Worship", "Workshops", "Sports"],
    tags: ["Interdenominational (Operation Mobilisation)", "Residential Event"],
    ageRange: "13-17",
    featured: true,
  },
  {
    id: "YA012",
    name: "WEC Summer Camps",
    website: "https://www.wecsummercamps.org.uk/",
    category: "youth",
    subCategory: "Residential Holidays",
    location: "Various UK locations",
    description: "First-class camping experience with Bible and missions teaching for young people. More than just a holiday.",
    denominationFocus: "Interdenominational (WEC International)",
    keyFeatures: ["Camping", "Bible teaching", "Missions focus", "Activities"],
    tags: ["Interdenominational (WEC International)", "Residential Holidays"],
    ageRange: "10-18",
  },
  {
    id: "YA013",
    name: "PGL Christian Youth Camps",
    website: "https://schoolsandgroups.pgl.co.uk/faith-groups/christian-youth-camps/",
    category: "youth",
    subCategory: "Outdoor Adventure",
    location: "Various UK locations",
    description: "PGL offers outdoor adventure Christian youth camps with dedicated prayer spaces and tailored itineraries for youth groups.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Outdoor adventure", "Prayer spaces", "Tailored itineraries"],
    tags: ["Interdenominational", "Outdoor Adventure"],
    ageRange: "8-17",
  },
  {
    id: "YA014",
    name: "Through the Roof (Accessible Holidays)",
    website: "https://throughtheroof.org/holidays-and-retreats/",
    category: "youth",
    subCategory: "Full Board Accessible",
    location: "Hampshire, Torquay",
    description: "Full-board accessible holidays for disabled people combining Christian worship, teaching and fellowship with tailored support.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Accessible accommodation", "Worship", "Teaching", "Fellowship", "Support workers"],
    tags: ["Interdenominational", "Full Board Accessible"],
    ageRange: "All ages",
    accessibility: "Full",
  },
  {
    id: "YA015",
    name: "Dreaming the Impossible (DTI)",
    website: "https://dreamingtheimpossible.org/",
    category: "youth",
    subCategory: "Residential Event",
    location: "Stafford",
    description: "5-day event run by Vineyard Churches UK & Ireland for young people aged 12-18.",
    denominationFocus: "Vineyard / Interdenominational",
    keyFeatures: ["Worship", "Teaching", "Activities", "Community"],
    tags: ["Vineyard", "Interdenominational", "Residential Event"],
    ageRange: "12-18",
    contactEmail: "[email protected]",
    contactPhone: "01159887067",
  },
  {
    id: "YA016",
    name: "Walrus Cruise",
    website: "https://www.walruscruise.org/",
    category: "youth",
    subCategory: "Sailing Holidays",
    location: "Norfolk Broads",
    description: "RYA Training Centre offering adventurous training sailing holidays for teenagers (13-18) and students on the Norfolk Broads.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Sailing", "RYA qualifications", "Bible studies", "Fellowship"],
    tags: ["Interdenominational", "Sailing Holidays"],
    ageRange: "13-18+",
  },
  {
    id: "YA017",
    name: "Christian Surfers UK",
    website: "https://www.christiansurfers.co.uk/",
    category: "youth",
    subCategory: "Surf Camps",
    location: "Cornwall/Various",
    description: "Serving the UK surfing community with national gatherings, camp-outs, and surf events combining surfing with worship.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Surfing", "Camping", "Worship", "Fellowship"],
    tags: ["Interdenominational", "Surf Camps"],
    ageRange: "All ages",
    contactPhone: "office@christiansurfers.co.uk",
    featured: true,
  },
  {
    id: "YA018",
    name: "Christian Adventures",
    website: "https://www.christianadventures.org/road-cycling",
    category: "youth",
    subCategory: "Cycling / Road",
    location: "Various",
    description: "Leads road cycling trips and adventures, providing top-quality bikes and leading groups to various destinations.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Road cycling", "Adventure travel", "Fellowship"],
    tags: ["Interdenominational", "Cycling"],
    ageRange: "Adults/Youth",
    contactPhone: "info@christianadventures.org",
  },
  {
    id: "YA019",
    name: "Great Wood Camp",
    website: "https://greatwood.org.uk/",
    category: "youth",
    subCategory: "Outdoor Adventure",
    location: "Quantocks, Somerset",
    description: "Modern forest venue with log cabins, ideal for groups, church weekends & hosts Scripture Union summer camps.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Log cabins", "Forest venue", "Group hire", "SU camps"],
    tags: ["Interdenominational", "Outdoor Adventure"],
    ageRange: "8-18+",
  },
  {
    id: "YA020",
    name: "Suffolk Christian Camps",
    website: "https://suffolkchristiancamps.org.uk/",
    category: "youth",
    subCategory: "Family / Youth Camps",
    location: "Suffolk",
    description: "Offers family camps and youth camps with activities, free time, and good food for all ages.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Camping", "Activities", "Fellowship", "Bible teaching"],
    tags: ["Interdenominational", "Family"],
    ageRange: "All ages",
  },
];

/** Festivals & events */
export const FESTIVALS: Provider[] = [
{
    id: "FE001",
    name: "Spring Harvest",
    website: "https://www.springharvest.org/",
    category: "festivals",
    subCategory: "Major Festival",
    location: "Minehead / Skegness",
    region: "National",
    country: "UK",
    description:
      "One of the UK's largest Christian festivals bringing tens of thousands of Christians together each Easter for worship, teaching and community.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Easter festival", "Worship", "Bible teaching", "Family programme"],
    tags: ["Interdenominational", "Easter", "Major Festival"],
    featured: true,
  },
  {
    id: "FE002",
    name: "Keswick Convention",
    website: "https://www.keswickministries.org/",
    category: "festivals",
    subCategory: "Bible Convention",
    location: "Keswick, Cumbria",
    region: "North West",
    country: "UK",
    description:
      "Historic annual Bible convention in the Lake District, drawing Christians from across the UK for three weeks of teaching, prayer and fellowship each July.",
    denominationFocus: "Interdenominational / Evangelical",
    keyFeatures: ["Bible teaching", "Three weeks", "Lake District", "Historic convention"],
    tags: ["Evangelical", "Bible Teaching", "Lake District"],
    featured: true,
  },
  {
    id: "FE003",
    name: "Big Church Festival",
    website: "https://www.bigchurchfestival.com/",
    category: "festivals",
    subCategory: "Music Festival",
    location: "Wiston Estate, West Sussex",
    region: "South East",
    country: "UK",
    description:
      "A major annual outdoor Christian music festival featuring world-class worship artists, camping, and family activities.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Camping", "Worship music", "Family activities", "World-class artists"],
    tags: ["Interdenominational", "Music", "Family", "Camping"],
    featured: true,
  },
  {
    id: "FE004",
    name: "New Wine",
    website: "https://www.new-wine.org/",
    category: "festivals",
    subCategory: "Summer Festival",
    location: "Multiple UK venues",
    region: "National",
    country: "UK",
    description:
      "Annual summer conference with a charismatic flavour, featuring worship, teaching and ministry for all ages.",
    denominationFocus: "Charismatic / Interdenominational",
    keyFeatures: ["Summer conference", "Ministry", "All ages", "Worship"],
    tags: ["Charismatic", "Summer", "All Ages"],
    featured: true,
  },
  {
    id: "FE005",
    name: "Greenbelt Festival",
    website: "https://www.greenbelt.org.uk/",
    category: "festivals",
    subCategory: "Arts Festival",
    location: "Boughton Estate, Northamptonshire",
    region: "East Midlands",
    country: "UK",
    description:
      "Annual festival celebrating arts, faith and justice in a stunning outdoor setting, combining music, art and Christian thought.",
    denominationFocus: "Progressive / Interdenominational",
    keyFeatures: ["Arts & music", "Justice themes", "Outdoor", "Camping"],
    tags: ["Progressive", "Arts", "Music"],
  },
  {
    id: "FE006",
    name: "David's Tent",
    website: "https://www.davidstent.net/",
    category: "festivals",
    subCategory: "Worship Gathering",
    location: "Charlton Park, Wiltshire",
    region: "South West",
    country: "UK",
    description: "Leading worship ministry gathering over 5000 believers for continuous worship and prayer.",
    denominationFocus: "Charismatic / Interdenominational",
    keyFeatures: ["August", "4 days", "Camping", "Leading worship ministry gathering over 5000 believers for continuous worship and prayer."],
    tags: ["Charismatic", "Interdenominational", "Worship Gathering"],
    targetAudience: "Worship enthusiasts, All ages",
    featured: true,
  },
  {
    id: "FE007",
    name: "Creation Fest",
    website: "https://creationfest.org.uk/",
    category: "festivals",
    subCategory: "Music Festival",
    location: "Royal Cornwall Events Centre, Wadebridge",
    region: "South West",
    country: "UK",
    description: "FREE music festival with faith talks, family fun, skate, and live music in Cornwall.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["FREE music festival with faith talks", "family fun", "skate", "and live music in Cornwall."],
    tags: ["Interdenominational", "Music Festival"],
    targetAudience: "Families, Young people, Local community",
    featured: true,
  },
  {
    id: "FE008",
    name: "Cliff Festival",
    website: "https://www.cliffcollege.ac.uk/festival",
    category: "festivals",
    subCategory: "Festival / Conference",
    location: "Cliff College, Derbyshire",
    region: "East Midlands",
    country: "UK",
    description: "Annual festival at Cliff College running for over a century. Worship, teaching, social events, and activities.",
    denominationFocus: "Methodist / Interdenominational",
    keyFeatures: ["Annual festival at Cliff College running for over a century. Worship", "teaching", "social events", "and activities."],
    tags: ["Methodist", "Interdenominational", "Festival"],
    targetAudience: "All ages, Families",
  },
  {
    id: "FE009",
    name: "Wildfires",
    website: "https://wildfiresfestival.com/",
    category: "festivals",
    subCategory: "Festival / Conference",
    location: "Wiston Estate, West Sussex",
    region: "South East",
    country: "UK",
    description: "Festival with vision to see revival sparked across the UK. Seminars, worship, and teaching.",
    denominationFocus: "Charismatic / Interdenominational",
    keyFeatures: ["Festival with vision to see revival sparked across the UK. Seminars", "worship", "and teaching."],
    tags: ["Charismatic", "Interdenominational", "Festival"],
    targetAudience: "Young adults, Church leaders",
  },
  {
    id: "FE010",
    name: "The Shift",
    website: "https://shift-uk.com/",
    category: "festivals",
    subCategory: "Festival / Gathering",
    location: "The Leigh, Gloucestershire",
    region: "South West",
    country: "UK",
    description: "Small-scale Christian gathering on a farm. Intimate worship, prayer, and fellowship.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Small-scale Christian gathering on a farm. Intimate worship", "prayer", "and fellowship."],
    tags: ["Interdenominational", "Festival"],
    targetAudience: "Adults, Small groups",
  },
  {
    id: "FE011",
    name: "New Horizon",
    website: "https://newhorizon.org.uk/",
    category: "festivals",
    subCategory: "Festival / Conference",
    location: "Coleraine, Northern Ireland",
    region: "Northern Ireland",
    country: "UK",
    description: "Major Northern Ireland Christian event with teaching, worship, youth programme, and Mission Hub.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Major Northern Ireland Christian event with teaching", "worship", "youth programme", "and Mission Hub."],
    tags: ["Interdenominational", "Festival"],
    targetAudience: "Families, Young people, Church leaders",
    featured: true,
  },
  {
    id: "FE012",
    name: "Cedarwood Festival",
    website: "https://cedarwoodfestival.com/",
    category: "festivals",
    subCategory: "Music Festival",
    location: "Thorp Perrow, North Yorkshire",
    region: "Yorkshire",
    country: "UK",
    description: "3-day Christian music and worship festival in North Yorkshire with vision to unite the body of Christ in the North.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["July", "3 days", "Camping", "3-day Christian music and worship festival in North Yorkshire with vision to unite the body of Christ in the North."],
    tags: ["Interdenominational", "Music Festival"],
    targetAudience: "All ages, Northern Christians",
  },
  {
    id: "FE013",
    name: "Catalyst Festival",
    website: "https://catalystnetwork.org/festival",
    category: "festivals",
    subCategory: "Festival / Conference",
    location: "Norwich, Norfolk",
    region: "East of England",
    country: "UK",
    description: "Festival about gathering, loving God and mission. Empowering attendees to make a difference in workplaces and communities.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Festival about gathering", "loving God and mission. Empowering attendees to make a difference in workplaces and communities."],
    tags: ["Interdenominational", "Festival"],
    targetAudience: "Church leaders, Missional Christians",
  },
  {
    id: "FE014",
    name: "Awaken (formerly Grapevine/ONE Event)",
    website: "https://awakenevent.uk/",
    category: "festivals",
    subCategory: "Festival / Conference",
    location: "Newark, Lincolnshire",
    region: "East Midlands",
    country: "UK",
    description: "Event for the Ground Level Network of Churches and friends. Teaching, worship, and community.",
    denominationFocus: "Ground Level / Interdenominational",
    keyFeatures: ["Event for the Ground Level Network of Churches and friends. Teaching", "worship", "and community."],
    tags: ["Ground Level", "Interdenominational", "Festival"],
    targetAudience: "Families, Church network",
  },
  {
    id: "FE015",
    name: "Bible by the Beach",
    website: "https://www.biblebythebeach.org/",
    category: "festivals",
    subCategory: "Conference",
    location: "Eastbourne, East Sussex",
    region: "South East",
    country: "UK",
    description: "High-quality Bible-centred conference for all God's people. Lively and contemporary in style.",
    denominationFocus: "Evangelical / Interdenominational",
    keyFeatures: ["April/May", "4 days", "Local hotels and B&Bs", "High-quality Bible-centred conference for all God's people. Lively and contemporary in style."],
    tags: ["Evangelical", "Interdenominational", "Conference"],
    targetAudience: "Adults, Families, Individuals",
  },
  {
    id: "FE016",
    name: "Commission Festival",
    website: "https://www.commission.global/festivalhome",
    category: "festivals",
    subCategory: "Festival / Conference",
    location: "Shepton Mallet, Somerset",
    region: "South West",
    country: "UK",
    description: "Brings together the Commission family of churches for teaching, worship, and encounters with God.",
    denominationFocus: "Commission / Interdenominational",
    keyFeatures: ["Brings together the Commission family of churches for teaching", "worship", "and encounters with God."],
    tags: ["Commission", "Interdenominational", "Festival"],
    targetAudience: "Church network, Families",
  },
  {
    id: "FE017",
    name: "Devoted",
    website: "https://devotedevent.org/",
    category: "festivals",
    subCategory: "Conference",
    location: "Stafford, Staffordshire",
    region: "West Midlands",
    country: "UK",
    description: "Bi-annual weekend event by ChristCentral churches under New Frontiers. Open to anyone.",
    denominationFocus: "New Frontiers / Interdenominational",
    keyFeatures: ["August", "3 days", "Camping; Local accommodation", "Bi-annual weekend event by ChristCentral churches under New Frontiers. Open to anyone."],
    tags: ["New Frontiers", "Interdenominational", "Conference"],
    targetAudience: "Young adults, Church network",
  },
  {
    id: "FE018",
    name: "Focus (HTB Network)",
    website: "https://focus.htb.org/",
    category: "festivals",
    subCategory: "Conference",
    location: "Newark, Nottinghamshire",
    region: "East Midlands",
    country: "UK",
    description: "Gathering of the HTB church network for teaching, worship, and community. Big Top worship and family programme.",
    denominationFocus: "HTB Network / Anglican",
    keyFeatures: ["Gathering of the HTB church network for teaching", "worship", "and community. Big Top worship and family programme."],
    tags: ["HTB Network", "Anglican", "Conference"],
    targetAudience: "HTB network, Families",
  },
  {
    id: "FE019",
    name: "EMW Aberystwyth Conference",
    website: "https://www.emw.org.uk/aber",
    category: "festivals",
    subCategory: "Conference",
    location: "Aberystwyth, Wales",
    region: "Wales",
    country: "UK",
    description: "1500 people gather to be refreshed by the Word. Welsh evangelical conference.",
    denominationFocus: "Evangelical / Welsh",
    keyFeatures: ["August", "7-14 days", "University accommodation; Local B&Bs", "1500 people gather to be refreshed by the Word. Welsh evangelical conference."],
    tags: ["Evangelical", "Welsh", "Conference"],
    targetAudience: "Welsh Christians, Families",
  },
  {
    id: "FE020",
    name: "Bangor Worldwide Missionary Convention",
    website: "https://www.worldwidemission.org/",
    category: "festivals",
    subCategory: "Conference",
    location: "Bangor, Northern Ireland",
    region: "Northern Ireland",
    country: "UK",
    description: "Annual 9-day missions conference held in Bangor, Northern Ireland. Focuses on global mission.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Annual 9-day missions conference held in Bangor", "Northern Ireland. Focuses on global mission."],
    tags: ["Interdenominational", "Conference"],
    targetAudience: "Mission-minded Christians",
  },
  {
    id: "FE021",
    name: "Essence Christian Creative Festival",
    website: "https://www.essencefest.org/",
    category: "festivals",
    subCategory: "Arts Festival",
    location: "Llanmadoc, Gower, South Wales",
    region: "Wales",
    country: "UK",
    description: "Family-friendly event encouraging creativity in God's people. Arts, crafts, music, and worship.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Family-friendly event encouraging creativity in God's people. Arts", "crafts", "music", "and worship."],
    tags: ["Interdenominational", "Arts Festival"],
    targetAudience: "Creative Christians, Families",
  },
  {
    id: "FE022",
    name: "Weekend to Remember (FamilyLife)",
    website: "https://www.familylife.com/weekend-to-remember/",
    category: "festivals",
    subCategory: "Conference / Retreat",
    location: "Various UK locations",
    region: "Various",
    country: "UK",
    description: "Faith-based marriage retreat offering tools to strengthen relationships and rebuild intimacy.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Various", "3 days", "Hotel accommodation", "Faith-based marriage retreat offering tools to strengthen relationships and rebuild intimacy."],
    tags: ["Interdenominational", "Conference"],
    targetAudience: "Married Couples",
  },
  {
    id: "FE023",
    name: "GoHealth Wilderness and Wellbeing Retreat",
    website: "https://gohealth.org.uk/wildernessandwellbeing/",
    category: "festivals",
    subCategory: "Retreat / Gathering",
    location: "Various UK locations",
    region: "Various",
    country: "UK",
    description: "Community gathering providing time and space to reflect on health and healing through connecting with nature.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Various", "3-5 days", "Retreat centres; Camping", "Community gathering providing time and space to reflect on health and healing through connecting with nature."],
    tags: ["Interdenominational", "Retreat"],
    targetAudience: "Adults",
  },
  {
    id: "FE024",
    name: "The Pilgrim's Way (Lent Retreats)",
    website: "https://www.turveyabbey.org.uk/pilgrimage/lent-retreats/",
    category: "festivals",
    subCategory: "Retreat / Event",
    location: "Turvey Abbey",
    region: "East of England",
    country: "UK",
    description: "Lent retreats and courses offering spiritual nourishment and support for the inner journey during the Lenten season.",
    denominationFocus: "Catholic / Interdenominational",
    keyFeatures: ["March/April (Lent)", "3-7 days", "Abbey accommodation", "Lent retreats and courses offering spiritual nourishment and support for the inner journey during the Lenten season."],
    tags: ["Catholic", "Interdenominational", "Retreat"],
    targetAudience: "Adults",
  },
];

/** Self-catering, B&Bs and home swap */
export const SELF_CATERING: Provider[] = [
{
    id: "SC001",
    name: "HolyHols",
    website: "https://www.holyhols.com/",
    category: "self-catering",
    subCategory: "Directory",
    location: "UK-wide",
    description:
      "Online directory connecting Christian property owners with holidaymakers, offering clergy discounts and faith-aligned self-catering accommodation.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Clergy discounts", "Self-catering", "Christian owners", "UK-wide"],
    tags: ["Interdenominational", "Self-catering", "Clergy Discount"],
    featured: true,
  },
  {
    id: "SC002",
    name: "Christian House & Church Swap (CHACS)",
    website: "https://www.chacs.co.uk/",
    category: "self-catering",
    subCategory: "Home Swap",
    location: "UK & Worldwide",
    description:
      "Affordable home exchange platform for Christians, facilitating house swaps between believers globally — ideal for budget-conscious families.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Home exchange", "Affordable", "Family-friendly", "International"],
    tags: ["Interdenominational", "Home Swap", "Budget"],
    featured: true,
  },
  {
    id: "SC003",
    name: "Christian Holiday Guide (Premier)",
    website: "https://growwithpremier.com/brands/christian-holiday-guide/",
    category: "self-catering",
    subCategory: "Holiday Guide",
    location: "UK",
    description: "The go-to space for Christians seeking faith-based holiday experiences and accommodation. Part of Premier Christian media group.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Part of Premier media network", "Holiday rentals", "Retreats", "Tour operators"],
    tags: ["Interdenominational", "Holiday Guide"],
  },
  {
    id: "SC004",
    name: "OSCAR Holiday Directory",
    website: "https://oscar.org.uk/resources/practical/accommodation/uk-accommodation/holidays-uk",
    category: "self-catering",
    subCategory: "Comprehensive Directory",
    location: "UK",
    description: "128+ resources covering hotels, B&Bs, self-catering, camping, retreat houses, organised holidays, and festivals for Christian workers.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Comprehensive categories", "Christian worker focus", "Free to browse", "128+ listings"],
    tags: ["Interdenominational", "Comprehensive Directory"],
  },
  {
    id: "SC005",
    name: "Christian Residential Network (CRNet)",
    website: "https://crnet.org.uk/",
    category: "self-catering",
    subCategory: "Residential Venues",
    location: "UK",
    description: "Association representing over 200 Christian residential venues, conference centres, and camps across the UK. Includes holiday search.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["200+ member venues", "Holiday search tool", "Conference centres", "Camps"],
    tags: ["Interdenominational", "Residential Venues"],
    featured: true,
  },
  {
    id: "SC006",
    name: "The Retreat Association",
    website: "https://www.retreats.org.uk/",
    category: "self-catering",
    subCategory: "Retreat Centres",
    location: "UK",
    description: "Directory of retreat centres across the UK with interactive Google map. Lists upcoming retreats and retreat centre profiles.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Interactive map", "Retreat centre directory", "Upcoming retreats listing"],
    tags: ["Interdenominational", "Retreat Centres"],
  },
  {
    id: "SC007",
    name: "Shunem Trust",
    website: "https://shunemtrust.org.uk/",
    category: "self-catering",
    subCategory: "Holiday Accommodation",
    location: "UK",
    description: "Provides free or subsidised holiday accommodation for Christian workers, missionaries, and clergy needing rest and refreshment.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Free/subsidised holidays", "For Christian workers", "Charity-funded"],
    tags: ["Interdenominational", "Holiday Accommodation"],
  },
  {
    id: "SC008",
    name: "Whitefield Christian Trust",
    website: "https://www.whitefieldchristiantrust.org.uk/",
    category: "self-catering",
    subCategory: "Holiday Accommodation",
    location: "UK",
    description: "Provides holiday accommodation and support for Christian workers and missionaries.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["For Christian workers", "Trust-funded accommodation"],
    tags: ["Interdenominational", "Holiday Accommodation"],
  },
  {
    id: "SC009",
    name: "Boaters' Christian Fellowship",
    website: "https://www.boaterschristianfellowship.org.uk/",
    category: "self-catering",
    subCategory: "Canal / Boating",
    location: "UK",
    description: "Network for Christians who enjoy the inland waterways. Includes membership directory and organises canal boat get-togethers.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Canal boating", "Membership directory", "Magazine"],
    tags: ["Interdenominational", "Canal"],
    featured: true,
  },
  {
    id: "SC010",
    name: "Caravanners and Campers Christian Fellowship (CCCF)",
    website: "https://www.cccf.org.uk/",
    category: "self-catering",
    subCategory: "Camping / Caravanning",
    location: "UK",
    description: "Fellowship organising rallies across the UK where believers meet in tents and caravans for fellowship and worship.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Camping rallies", "Motorhome friendly", "Regional groups"],
    tags: ["Interdenominational", "Camping"],
  },
];

/** Missions & voluntourism */
export const MISSIONS: Provider[] = [
  {
    id: "MI001",
    name: "Operation Mobilisation (OM)",
    website: "https://www.uk.om.org/pages/category/options-to-join",
    category: "missions",
    subCategory: "Short-Term Missions",
    location: "UK",
    description: "Offers short-term mission trips ranging from one week to several months, allowing UK Christians to serve overseas.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["One week to several months", "Overseas service", "UK-based organisation"],
    tags: ["Interdenominational", "Missions", "Overseas"],
    targetAudience: "Individuals, Groups",
    featured: true,
  },
  {
    id: "MI002",
    name: "Youth With A Mission (YWAM)",
    website: "https://www.ywam.org/",
    category: "missions",
    subCategory: "Short-Term Missions",
    location: "UK",
    description: "Global missions organisation offering short-term mission trips and training for UK Christians to serve overseas.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Short-term missions", "Global network", "Training programmes"],
    tags: ["Interdenominational", "Missions", "Youth"],
    targetAudience: "Young adults, Individuals",
  },
  {
    id: "MI003",
    name: "Mission Direct",
    website: "https://missiondirect.org/",
    category: "missions",
    subCategory: "Voluntourism",
    location: "UK",
    description: "Specialises in two-week overseas mission trips for UK volunteers to build homes or schools in developing nations.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Two-week trips", "Building projects", "Developing nations"],
    tags: ["Interdenominational", "Voluntourism", "Building"],
    targetAudience: "Volunteers, Church groups",
    featured: true,
  },
  {
    id: "MI004",
    name: "Compassion International",
    website: "https://www.compassion.com/get-involved/field-experiences/",
    category: "missions",
    subCategory: "Charity Field Trips",
    location: "UK/International",
    description: "Runs Field Experiences, allowing sponsors to travel in groups to visit the children they sponsor and see the charity's work firsthand.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Sponsor visits", "Group travel", "Charity field experiences"],
    tags: ["Interdenominational", "Charity", "Sponsors"],
    targetAudience: "Sponsors, Donors",
  },
  {
    id: "MI005",
    name: "Tearfund",
    website: "https://www.tearfund.org/",
    category: "missions",
    subCategory: "Discovery Team Trips",
    location: "UK",
    description: "Runs Discovery Team trips designed to help church leaders and donors understand their humanitarian work.",
    denominationFocus: "Interdenominational",
    keyFeatures: ["Discovery Team trips", "Humanitarian work", "Church leaders"],
    tags: ["Interdenominational", "Humanitarian", "Discovery"],
    targetAudience: "Church leaders, Donors",
  },
];

/** All providers combined */
export const ALL_PROVIDERS: Provider[] = [
  ...TOUR_OPERATORS,
  ...RETREATS,
  ...YOUTH_CAMPS,
  ...FESTIVALS,
  ...SELF_CATERING,
  ...MISSIONS,
];

export function getProvidersByCategory(category: Provider["category"]): Provider[] {
  return ALL_PROVIDERS.filter((p) => p.category === category);
}

export function getFeaturedProviders(): Provider[] {
  return ALL_PROVIDERS.filter((p) => p.featured);
}

export function getProviderById(id: string): Provider | undefined {
  return ALL_PROVIDERS.find((p) => p.id === id);
}

export function getRelatedProviders(provider: Provider, limit = 3): Provider[] {
  return ALL_PROVIDERS.filter(
    (p) => p.id !== provider.id && p.category === provider.category
  ).slice(0, limit);
}
